version = 0.1
[UAT]
[UAT.deploy]
[UAT.deploy.parameters]
stack_name = "VirtualSlideViewer-logic-UAT"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3okyxt2msf06"
s3_prefix = "vsv-backend-UAT"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VpcId=vpc-0debc1e15b05d7340 Subnets=subnet-0f64acc617311f0a9,subnet-019899523293b0e59 FileSystem=fs-f79efd8f SecurityGroup=sg-0d1ca19af4ca5d388 AccessPointId=fsap-0f490959b113da139 AccessPointArn=\"arn:aws:elasticfilesystem:us-east-2:839559484193:access-point/fsap-0f490959b113da139\" EnvType=\"UAT\" StageName=\"test\" AllowOrigin=\"https://path-uat.cptac.vai.org\" ImagesPath=\"/mnt/lambda\" TableName=\"VsvSlideTable\""