version = 0.1
[UAT]
[UAT.deploy]
[UAT.deploy.parameters]
stack_name = "VirtualSlideViewer-db-UAT"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3okyxt2msf06"
s3_prefix = "vsv-backend-UAT"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"