AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'VPC resources for Virtual Slide Viewer'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Region Config
      Parameters:
      - RegionAZ1Name
      - RegionAZ2Name
    - Label:
        default: VPC Config
      Parameters:
      - CIDR
      - SubnetACIDR
      - SubnetBCIDR
    ParameterLabels:
      CIDR:
        default: VPC CIDR block
      SubnetACIDR:
        default: CIDR block of A subnet
      SubnetBCIDR:
        default: CIDR block of B subnet
Parameters:
  StackName:
    Description: Name of the parent of this nested stack.
    Type: String
  RegionAZ1Name:
    Description: Availability Zone 1 Name in Region
    Type: String
  RegionAZ2Name:
    Description: Availability Zone 2 Name in Region
    Type: String
  CIDR:
    Description: CIDR block for  VPC
    Type: String
  SubnetACIDR:
    Description: CIDR block for AZ-1b subnet
    Type: String
  SubnetBCIDR:
    Description: CIDR block for AZ-1b subnet
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDR
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Ref StackName
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Ref VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Ref StackName
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - VPCGatewayAttachment
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetACIDR
      AvailabilityZone: !Ref RegionAZ1Name
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: Subnet A
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetBCIDR
      AvailabilityZone: !Ref RegionAZ2Name
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: Subnet B
  RouteAssocA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetA
  RouteAssocB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetB

Outputs:
  VpcId:
    Description: 'The ID of the created Virtual Private Cloud (VPC)'
    Value: !Ref VPC
  SubnetIds:
    Description: 'The list of created subnet IDs, for at least two Availability Zones in the region in your Virtual Private Cloud (VPC)'
    Value: !Join [',', [!Ref SubnetA, !Ref SubnetB]]
  RouteTableId:
    Description: 'The ID of the created route table of the VPC'
    Value: !Ref RouteTable
  